### ISSUE TITLE
#19 MUTATE: `Game.js` Remove new class as members

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/terni-lapilli--toe#19]
#MUTATE: 

- Remove reduncancies in class propagation. 
 - 1 GamePioeces instance
 - 1 GameBoard instance
-  1 GameLogic instance
- Only Initialise these on each start button click
- Testing saw multiple class instances and 
- Debugger looped throught each of these
- IN JS one class instance !== new class's instance, 
   they are different object 
- Objective: to have one instance per game instance

#### Todo

- [ ] Switch Game class props to undefened
- [ ] Debug the onInit() for these and check for error
- [ ] REMOVE these debuggers and Consol loggers
- [ ] Stepwise throught the code using `debugger`
- [ ] NoTe any isssue (==FAIL) or absence off (== Pass)

[terni-lapilli--toe] lib/__Game.js (Lines 62-67)

```

    // gamePieces = new GamePieces(this.Player1, this.Player2); /* ?+*/
    gamePieces;
    // gameBoard = new GameBoard(); /* ?+*/
    gameBoard;
    // gameLogic = new GameLogic(this.gameBoard, this.gamePieces); /* ?+*/
    gameLogic;
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/oHBeF90BSAeEsxogjhx_qQ?marker=64257279573e7982eefaf663&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/44d05b469897dca2aa38b1007a46a1285f304b1c/lib/__Game.js#L62-L67)
[terni-lapilli--toe] lib/__Game.js (Lines 104-138)

```

    onInit(log = this.logLevel, locname = `${this.fileName}: onInit`) {
        const logs = 1;
        if (!this.gameRunning) {
            debugger; /** TODO REMOVE */
            this.gameRunning = true;
            if (this.gameRunning) {
                // 2: Assign the game's pieces to a) the current game players and b)  up a new board
                // debugger
                this.gamePieces = new GamePieces(this.Player1, this.Player2); /* ?+*/
                this.gameBoard = new GameBoard(); /* ?+*/
                // 3: Link the current board and current pieces to the game logic
                this.gameLogic = new GameLogic(this.gameBoard, this.gamePieces); /* ?+*/
                this.deBug._debug(
                    this.gameBoard,
                    `Undefined Game Board set`,
                    logs,
                    `${locname}: Board`
                ); /** TODO REMOVE */
                this.deBug._debug(
                    this.gamePieces,
                    `Undefined GamePieces set`,
                    logs,
                    `${locname}: Pieces`
                ); /** TODO REMOVE */
                this.deBug._debug(
                    this.gameLogic,
                    `Undefined Game Logic  set`,
                    logs,
                    `${locname}: Logic`
                ); /** TODO REMOVE */
            }
        }
        // 4: Game is logging to the console at error level 9
        // this.gameLogger(log, `${locname}: onInit`);
    }
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/oHBeF90BSAeEsxogjhx_qQ?marker=64257279573e7982eefaf664&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/44d05b469897dca2aa38b1007a46a1285f304b1c/lib/__Game.js#L104-L138)
[terni-lapilli--toe] lib/App.js (Lines 94-104)

```

        // Set new Game instance
        try {
            this.newGame = new Game("X", "O", logr, `${locname}: new Game`);
            // this.newGame.Player1 = this.newGame.gamePieces.setX("X");
            // this.newGame.Player2 = this.newGame.gamePieces.setX("Y");
            // console.log(this.newGame.gamePieces.getX("X"));
            // console.log(this.newGame.gamePieces.getY("Y"));
        } catch (e) {
            // Throw a general error (errFlag1) on exceptions to new instance of a class, and log level 9 to console
            this.onError(e, 1, this.errorLevel, `${locname}: new Game`);
        }
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/oHBeF90BSAeEsxogjhx_qQ?marker=64257279573e7982eefaf665&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/8ac09b8fa5891ee97bcab2cf8dd71378d5c6cd67/lib/App.js#L94-L104)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
