### ISSUE TITLE
PP2 Javascript Essentials

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/terni-lapilli--toe#33]
### ToDo - Design an interactive Front-End web application using HTML and CSS and JavaScript based on the principles of user experience design, accessibility and responsivity

- [ ] [1.1](#1.1) ☑️❓ Design a web application that: ...
  - [ ] ☑️❓❌ Meets accessibility guidelines, ...
  - [ ] ☑️❓❌ Follows the principles of UX design and ...
  - [ ] ☑️❓❌ Presents a structured layout and navigation model, and ...
  - [ ] ☑️❓❌ Meets its given purpose.
- [ ] [1.2](#1.2) Design a website that
  - [ ] ☑️❓❌meets accessibility guidelines
    - [ ] ☑️❓❌e.g. contrast between background and foreground colours to cater for the visually impaired.
  - [ ] ☑️❓❌Optionally, add alt text for non-text elements
- [ ] [1.3](#1.2) ☑️❓❌Design the organisation of information on the page
  - [ ] ☑️❓❌ following the principles of user experience design ...
    - [x]  ☑️Headers are used to convey structure, ...
    - [ ]  ☑️In terms of priority, information is easy to find ..
      - [ ]  ☑️Due to being presented well.
      - [ ]  ☑️Due to being categorised well.
- [x] [1.4](#1.4) ☑️ Ensure that foreground information is never distracted by backgrounds. Done
- [ ] [1.5](#1.5) ☑️❓❌Include graphics that are consistent in style and colour. **WIP**
- [x] [1.6](#1.6) ☑️❓❌Design interactivity for a web application that ... **WIP**
  - [ ] ☑️❓Lets the user initiate and control actions WIP
  - [x] ☑️❓That gives feedback (Windows alerts), WIP.
- [x] [1.7](#1.7)☑️❓Write custom JavaScript, HTML and CSS code to ...
  - [x] ☑️ Create a responsive front-end web application consisting of **one** ~~or more~~ HTML page~~s~~.
  - [ ] ☑️❓❌ with significant interactive functionality
- [ ] [1.8](#1.8) ❌Write ***JavaScript code to produce relevant responses to user actions***
- [x] [1.9](#1.9)☑️ Implement an interactive web application that
  - [x]  ☑️❓❌ Incorporates images or graphics of usable resolution,
  - [x]  ☑️❓❌ Legible, unobscured text.
  - [x]  ☑️❓❌ Consistent styling.
  - [x]  ☑️❓❌ Undistracted foregrounds

[terni-lapilli--toe] _documentation/done.md (Lines 19-51)

```

## Definition of Done: v0.0.1, 2023.03.01: Pass Grade - MVP

### ToDo - Design an interactive Front-End web application using HTML and CSS and JavaScript based on the principles of user experience design, accessibility and responsivity

- [ ] [1.1](#1.7) ☑️❓ Design a web application that: ...
  - [ ] ☑️❓❌ Meets accessibility guidelines, ...
  - [ ] ☑️❓❌ Follows the principles of UX design and ...
  - [ ] ☑️❓❌ Presents a structured layout and navigation model, and ...
  - [ ] ☑️❓❌ Meets its given purpose.
- [ ] [1.2](#1.2) Design a website that
  - [ ] ☑️❓❌meets accessibility guidelines
    - [ ] ☑️❓❌e.g. contrast between background and foreground colours to cater for the visually impaired.
  - [ ] ☑️❓❌Optionally, add alt text for non-text elements
- [ ] [1.3](#1.2) ☑️❓❌Design the organisation of information on the page
  - [ ] ☑️❓❌ following the principles of user experience design ...
    - [x]  ☑️Headers are used to convey structure, ...
    - [ ]  ☑️In terms of priority, information is easy to find ..
      - [ ]  ☑️Due to being presented well.
      - [ ]  ☑️Due to being categorised well.
- [ ] [1.4](#1.4) ☑️❓❌Ensure that foreground information is never distracted by backgrounds.
- [ ] [1.5](#1.5) ☑️❓❌Include graphics that are consistent in style and colour.
- [ ] [1.6](#1.6) ☑️❓❌Design interactivity for a web application that ...
  - [ ] ☑️❓❌Lets the user initiate and control actions ...
  - [ ] ☑️❓❌That gives feedback.
- [ ] [1.7](#1.7)☑️❓❌Write custom JavaScript, HTML and CSS code to ...
  - [ ] ☑️❓❌ Create a responsive front-end web application consisting of **one** ~~or more~~ HTML page~~s~~.
  - [ ] ☑️❓❌ with significant interactive functionality
- [ ] [1.8](#1.8) ☑️❓❌Write ***JavaScript code to produce relevant responses to user actions***
- [ ] [1.9](#1.9)☑️❓❌Implement an interactive web application that
  - [ ]  ☑️❓❌ Incorporates images or graphics of usable resolution,
  - [ ]  ☑️❓❌ Legible, unobscured text.
  - [ ]  ☑️❓❌ Consistent styling.
  - [ ]  ☑️❓❌ Undistracted foregrounds
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/8gPkBqpqSu6pVybYYEwLcw?marker=643917c765ed53b20b13e8b8&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/ba24e888305c57e9c69bc99da4f7389b6797c68a/_documentation/done.md#L19-L51)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
