### ISSUE TITLE
LO2: PP2 Javascript Essentials:  Test a front-end web application through the development, implementation and deployment stages

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/terni-lapilli--toe#34]
## Leanrning Objective 2: ### To Do - Test a front-end web application through the development, implementation and deployment stages

- [x] [2.1](#2.1) ☑️**Write JavaScript code that passes through a linter (e.g. Jshint) with no significant issues.**
  - [x] Check.create validation reports from JSHint. See Readme (section [6.3.3](Readme.md#6.3.3)
  - [x] Raw [Report Data Validation Reports](/_documentation/validation) folder

- [x] [2.2](#2.2) ☑️ Write custom HTML code that passes through the official W3C validator with no issues.
  - [ ] 2023/04/14:
- [x] [2.3](#2.3) ❓ Write custom CSS code that passes through the official (Jigsaw) validator with no issues 
  - [ ] 2023/04/14:

- [❓] [2.4](#2.4) ☑️*Code all external links to open in a separate tab when clicked* 
   - [x] ☑️=> Using no external links, unless for history of the game content.

- [x] [2.5](#2.5) ☑️❓ *Use CSS media queries across the application to*
  - [x]  ☑️❓ ensure the layout changes appropriately 
  - [x]  ☑️❓ maintains the page's structural integrity across device screen sizes.: 
   1. Laptop: Fixed: > 968px
   2: iPad/Tablet: 448px - 968px
   3: iPhone/Mobile < 448px 
- [x] [2.6](#2.6) ☑️ Use Semantic mark-up to structure HTML code
- [ ] [2.7](#2.7) ❌ Present the *un*finished website with
  - [x] ☑️Clearly understandable site-specific content, ~~rather than Lorem Ipsum placeholder text~~
- [x] [2.8](#2.8) ☑️ If used, implement clear navigation to
  - [x] Presents a button and a grid of 3x3 on a single page
  - [ ] ❌ allow users to find resources on the site intuitively.

[terni-lapilli--toe] _documentation/done.md (Lines 53-66)

```

### To Do - Test a front-end web application through the development, implementation and deployment stages

- [❓] [2.1](#2.1) ☑️❓❌**Write JavaScript code that passes through a linter (e.g. Jshint) with no significant issues.**
- [x] [2.2](#2.2) ☑️ Write custom HTML code that passes through the official W3C validator with no issues.
- [x] [2.3](#2.3) ❓ Write custom CSS code that passes through the official (Jigsaw) validator with no issues => See ADLog.md for Code Decision on this.
- [❓] [2.4](#2.4) ☑️❓*Code all external links to open in a separate tab when clicked* => Using no external links, unless for history of the game content.
- [ ] [2.5](#2.5) ☑️❓ *Use CSS media queries across the application to*
  - [ ]  ☑️❓ ensure the layout changes appropriately and ..
  - [ ]  ☑️❓ maintains the page's structural integrity across device screen sizes.
- [x] [2.6](#2.6) ☑️ Use Semantic mark-up to structure HTML code
- [ ] [2.7](#2.7) ☑️❓ Present the finished website with
  - [x] ☑️Clearly understandable site-specific content, ~~rather than Lorem Ipsum placeholder text~~
- [ ] [2.8](#2.8) ☑️❓ If used, implement clear navigation to
  - [ ] ☑️❓ allow users to find resources on the site intuitively.
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/OypEqQFrRQCV2tAx7r9n1g?marker=64391a462fd202ecd4a3cb73&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/ba24e888305c57e9c69bc99da4f7389b6797c68a/_documentation/done.md#L53-L66)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
