### ISSUE TITLE
LO3: PP2 JavaScript Essentials: Deploy a Front-End web application to a Cloud platform

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/terni-lapilli--toe#35]
### ToDo - Deploy a Front-End web application to a Cloud platform

- [] [3.1](#3.1) ☑️❓Deploy a ~~final~~ version (v0.5.0) of the code
  - [x] ☑️to a cloud-based hosting platform (e.g. GitHub Pages) and
  - [ ] ❌ test to ensure it matches the development version
- [x] [3.2](#3.1) ☑️ Use Git & GitHub for version control of an interactive web application up to deployment.
- [x] [3.3](#3.3) ☑️ Remove commented out code ...
  - [x] ☑️ before pushing final changes to version control and deploying.
- [x] [3.4](#) ☑️Ensure that there are no broken internal links 

[terni-lapilli--toe] _documentation/done.md (Lines 68-76)

```

### ToDo - Deploy a Front-End web application to a Cloud platform

- [x] [3.1](#3.1) ☑️❓Deploy a final version of the code
  - [x] ☑️to a cloud-based hosting platform (e.g. GitHub Pages) and
  - [ ] ☑️❓test to ensure it matches the development version
- [x] [3.2](#3.1) ☑️ Use Git & GitHub for version control of an interactive web application up to deployment.
- [ ] [3.3](#3.3) ☑️❓❌ Remove commented out code ...
  - [ ] ☑️❓❌ before pushing final changes to version control and deploying.
- [x] [3.4](#) ☑️Ensure that there are no broken internal links => There are no internal links: See ADLog.md
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/6_yNBFZQSSShwir2DRlr6g?marker=64391ade337b5be66c3570a0&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/ba24e888305c57e9c69bc99da4f7389b6797c68a/_documentation/done.md#L68-L76)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
