### ISSUE TITLE
LO4: PP2: JavaScript Essentials: Maximise future maintainability through documentation, code structure and organisation

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/terni-lapilli--toe#36]
### **DONE** - Maximise future maintainability through documentation, code structure and organisation

- [x] [4.1](#4.1)   Write a README.md file for the web application that
  - [x] ☑️ Explains its purpose ...
  - [x] ☑️ The value that it provides to its users, and ...
  - [x] ☑️ The deployment procedure.
- [X] [4.2](#4.2) ☑️  Insert screenshots of the project features (err. code features) ...
  - [x] ☑️ Give a brief description of what each feature does and ...
    - [x] Use of the Gherkin syntax for `Feature`, `Scenario`, `Given`, `When`, `Then`, `And`

  - [x] ☑️ Explain its value to the user.: 
     1. `Scenarios` give the in the flow benefit of the task to the user
     2. Game and Product benefits outlines 
- [x] [4.3](#4.3) ☑️️ Attribute all code from external sources to its original source
  - [x]☑️ Via comments above the code and ...
  - [x] ☑️ For larger dependencies in the README.
- [x] [4.4](#4.4) ☑️ Clearly separate and identify ...
  - [x] ☑️ Code written for the website and ...
  - [x] ☑️ Code from external sources (e.g. libraries or tutorials)
- [x] 4.5 ☑️ Organise HTML, CSS and JavaScript code into well-defined and commented sections
   - [x] HTML : Light Comments
   - [x] CSS - Light style of documentation using @layers for well-defined code sections and labels comments in code. Notations to use a CUBE framework as an object not full realised.
   - [x] JSDoc for JavaScript Documentation
- [x] [4.6](#4.6) ☑️Place CSS code in external files linked to the HTML page in the HEAD element.
- [x] [4.7](#4.7) ☑️  Place JavaScript code in external files linked to the HTML page ***just above the closing body tag***.
- [x] [4.8](#4.8) ☑️Write code that meets at least minimum standards for readability
  - [x] ☑️ Consistent indentation ...
  - [x] ☑️ Blank lines only appear individually or, at most, in pairs
- [x] [4.9](#4.9) ☑️  Name files ...
  - [x] ☑️ Consistently and descriptively,
  - [x] ☑️ Without spaces or capitalisation to allow for cross-platform compatibility.
- [x] [4.10](#4.10) ☑️  Group files in directories by file type
  - [x] ☑️ e.g. an assets directory will contain all static files and may be organised into sub-directories such as CSS, images, etc.

[terni-lapilli--toe] _documentation/done.md (Lines 78-103)

```

### ToDo - Maximise future maintainability through documentation, code structure and organisation

- [x] [4.1](#4.1)   Write a README.md file for the web application that
  - [x] ☑️❓❌ Explains its purpose ...
  - [x] ☑️❓❌ The value that it provides to its users, and ...
  - [x] ☑️❓ ❌The deployment procedure.
- [ ] [4.2](#4.2) ☑️❓❌  Insert screenshots of the project features ...
  - [ ] ☑️❓❌ Give a brief description of what each feature does and ...
  - [x] ☑️❓❌ Explain its value to the user.
- [x] [4.3](#4.3) ☑️  Attribute all code from external sources to its original source
  - [ ]☑️ Via comments above the code and ...
  - [x] ☑️ For larger dependencies in the README.
- [x] [4.4](#4.4) ☑️❓❌  Clearly separate and identify ...
  - [x] ☑️ Code written for the website and ...
  - [x] ☑️ Code from external sources (e.g. libraries or tutorials)
- [ ] 4.5 ☑️❓❌  Organise HTML, CSS and JavaScript code into well-defined and commented sections
- [x] [4.6](#4.6) ☑️Place CSS code in external files linked to the HTML page in the HEAD element.
- [x] [4.7](#4.7) ☑️  Place JavaScript code in external files linked to the HTML page ***just above the closing body tag***.
- [x] [4.8](#4.8) ☑️❓  Write code that meets at least minimum standards for readability
  - [x] ☑️❓ Consistent indentation ...
  - [x] ☑️❓ Blank lines only appear individually or, at most, in pairs
- [x] [4.9](#4.9) ☑️  Name files ...
  - [x] ☑️ Consistently and descriptively,
  - [x] ☑️ Without spaces or capitalisation to allow for cross-platform compatibility.
- [x] [4.10](#4.10) ☑️  Group files in directories by file type
  - [x] ☑️ e.g. an assets directory will contain all static files and may be organised into sub-directories such as CSS, images, etc.
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/dXp1TS6ySW21O5nICLdc_Q?marker=64391d3a2c968ab60a75f11d&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/ba24e888305c57e9c69bc99da4f7389b6797c68a/_documentation/done.md#L78-L103)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
