### ISSUE TITLE
LO5: PP2 Javascript Essentials: Demonstrate and document the development process through a version control system such as GitHub

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/terni-lapilli--toe#37]
### ToDo - Demonstrate and document the development process through a version control system such as GitHub

- [x] [5.1](#5.1) ☑️ Use consistent and effective markdown formatting that is ... when writing a README file:
  - [x] ☑️ Well-structured, ...
  - [x] ☑️ Easy to follow, and ...
  - [ ] ☑️❓ Has few grammatical errors. (As a dyslexic, i seek some flexibility). Best efforts.
   - [x] Use: cSpell VSCode extension
   - [x] Use 
LanguageTool - Your writing assistant: Chrome/Edge browser extension when in gitpod

- Additionally used 
 - [x] ☑️ Conventional Changelog as a Human readable code change control/project log
 - [x] ☑️ SemVer, or an approximation, for each code variant: Major/Minor/Patch/Commit per day count
 - [x] ☑️ SemVer in JSDoc @version @date for code alignment with changelog.

[terni-lapilli--toe] _documentation/done.md (Lines 105-110)

```

### ToDo - Demonstrate and document the development process through a version control system such as GitHub

- [x] [5.1](#5.1) ☑️❓ Use consistent and effective markdown formatting that is ... when writing a README file:
  - [x] ☑️❓ Well-structured, ...
  - [x] ☑️❓ Easy to follow, and ...
  - [ ] ☑️❓ Has few grammatical errors.
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/y4_AM-mdS9quRvbrFFt4Jg?marker=64391f607dbea4b89e0bc8e3&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/ba24e888305c57e9c69bc99da4f7389b6797c68a/_documentation/done.md#L105-L110)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
