### ISSUE TITLE
LO6: PP2: JavaScript Essentials: Implement Front-End interactivity, using core JavaScript, JavaScript libraries or frameworks

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/terni-lapilli--toe#38]
### **DONE 80%* - Implement Front-End interactivity, using core JavaScript, JavaScript libraries or frameworks: *NOT DONE:* Testing

- [x] [6.1](#6.1) ☑️ **Write JavaScript functions that** *[Author]*
  - [x] ☑️**correctly implement compound statements, such as if conditions and loops.** *[Author]*
 -  [x] ☑️**correctly implement compound statements, switch cases, object maps as alternate switch case.** *[Author]*
 -  [x] ☑️** implement Immediately Invoke Executing Functions, function closures, arrow functions.** *[Author]*
 -  [x] ☑️** implement object model function binding for state checking in conditionals,  loops** *[Author]*
- [x] [6.2](#6.2) ☑️  **Write code that intelligently handles empty or invalid input data.** *[Author]*
  - [x] ☑️ Use of Input validation for Object | null or guard states against undefined. *[Author]*
  - [x] ☑️ Use of Type validation for Object | null or guard states against undefined, string, number for events and other user generated inputs. *[Author]*
  - [x] ☑️ Use of throwing custom error or returning errors to caller for graceful error handling *[Author]*
  - [x] ☑️ Use of Finite states management to gracefully handle errors (or plan to, as not yet implemented) *[Author]*
  - [x] ☑️ Use of Dedicated error handling functions *[Author]*
  - [x] ☑️ Use of Nullish coalesing operators *[Author]*

  - [x] ☑️ Use of defensive statements *[Author]*
  - [x] ☑️ Use of debugging classes and functions *[Author]*
  - [x] ☑️ Use of try ... catch and error handling statements *[Author]*
- [ ] [6.3](#6.3) ❌ **Implement appropriate working functionality for all project requirements.**
  - [x] ☑️ Project Requirements implemented as designed in Gherkin's `Feature Scenario` syntax, per Readme
  - [ ] ❌ Project requirements not appropriately working

- [ ] [6.4](#6.4) ❌ **Write code that does not generate internal errors on the page or in the console due to user actions.**
 -- Testing not proven this out by submission date
- [x] [6.5](#6.5) ☑️ **Organise code and assets files in directories by file type.**

[terni-lapilli--toe] _documentation/done.md (Lines 112-124)

```

### ToDo - Implement Front-End interactivity, using core JavaScript, JavaScript libraries or frameworks

- [x] Date: 203-03-11 6.1, 6.2, 6.5

- [x] [6.1](#6.1) ☑️ **Write JavaScript functions that**
  - [x] ☑️**correctly implement compound statements, such as if conditions and loops.**
- [x] [6.2](#6.2) ☑️  **Write code that intelligently handles empty or invalid input data.**
  - [x] ☑️ Use of defensive statements [Author]
  - [x] ☑️ Use of debugging classes and funcions [Author]
  - [x] ☑️ Use of try ... catch and error handling statements [Author]
- [ ] [6.3](#6.3) ☑️❓❌  **Implement appropriate working functionality for all project requirements.**
- [ ] [6.4](#6.4) ☑️❓❌ **Write code that does not generate internal errors on the page or in the console due to user actions.**
- [x] [6.5](#6.5) ☑️ **Organise code and assets files in directories by file type.**
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/6EIoviL7S_SQlNFRmtqi_w?marker=6439229b76af90a53470759c&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/ba24e888305c57e9c69bc99da4f7389b6797c68a/_documentation/done.md#L112-L124)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
