### ISSUE TITLE
#9 [REFACTOR] `MoveListener.js` Inspect and reflect #4, #7 for customEvent Listener pattern

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/terni-lapilli--toe#9]
### Inspect, Reflect same approach for StartListener.

- Variant: There are many types of these for each move, and multple html nodelist elements and not just a button click.

#### Todo

- [ ] Inspect the class props
- [ ] Inspect the class constructor
- [ ] Inspect the class setListener
- [ ] Add an onInit or alterativefor binding in / at `App.js`
- [ ] State where the `Game.js` is updated with the move

#### Tests

- Check in browser/IDE console for errors
- Check for the following assertions
  1. If I click on a cell, a value is updated to the UI
  2. If i click on a cell, the logic checks if there a win or draw state
  3. If I click on a cell, the next turn function is called
  4. If I click on a sequence of a cells, then the above is repeats untl a win
  5. If I click on a sequence of a cells, then the above is repeats untl a draw

#### Next
- Move on to the next issue, file: `GameLogic.js`
  
#### Related
See #3, #4, #5, #7

[terni-lapilli--toe] lib/__MoveListener.js (Lines 57-69)

```

  constructor(moves, game, evnt, locname = `Move Listener Constructor`) {
        this.userMoves = this.evaluateParameter(moves, 1, 10);
        this.newGame = this.evaluateParameter(game, 2, 10);
        this.eventType = this.evaluateEventType(evnt, 1, 10);

        try {
            // Assign Moves Listener on a Move
            this.setListeners(this.userMoves, 3);
            this.onMove = this.onMove.bind(this);
        } catch (error) {
            this.onError(e, 5, 9, `${locname}`);
        }
    }
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/vI0jyeAGRcq-WO6kRwMOLw?marker=641ef44b45278d81dddabc36&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/472e4fb0b57589c9a093620f445f8ee4880f715f/lib/__MoveListener.js#L57-L69)
[terni-lapilli--toe] lib/__MoveListener.js (Lines 85-99)

```

    setListeners(nodes, log = 1, locname = `${this.fileName}: SetListener`) {
        nodes.forEach((cell) => {
            // For each cell, (node | tile), add an event listener, assign the move to the listner and attatch to the game.
            cell.addEventListener(this.eventType, () => {
                this.onMove(cell.dataset.index);
                //Attatch debugger to the console and info output
                this.deBug._debug(
                    cell,
                    `Cell ${cell.dataset.index} attatches an ${this.eventType}. Waiting for...`,
                    log,
                    `${locname}`
                );
            });
        });
    }
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/vI0jyeAGRcq-WO6kRwMOLw?marker=641ef44b45278d81dddabc38&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/472e4fb0b57589c9a093620f445f8ee4880f715f/lib/__MoveListener.js#L85-L99)
[terni-lapilli--toe] lib/__MoveListener.js (Lines 40-44)

```

    deBug = new GameDebug();
    userMoves = document.querySelectorAll(".cell");
    newGame = new Game("X", "O");
    eventType = "";
    fileName = "MoveListener.js";
```

[Open in IDE](https://api.codestream.com/c/ZBNk4xDOQ2o6RTpe/vI0jyeAGRcq-WO6kRwMOLw?marker=641ef44b45278d81dddabc39&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ipoetdev/terni-lapilli--toe/blob/472e4fb0b57589c9a093620f445f8ee4880f715f/lib/__MoveListener.js#L40-L44)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
